# We have a conf and classes directory, add to BBPATH.
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES.
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb"

BBFILE_COLLECTIONS += "freebsd"
BBFILE_PATTERN_freebsd = "^${LAYERDIR}/"
BBFILE_PRIORITY_freebsd = "6"

LAYERSERIES_COMPAT_freebsd = "blacksail"
LAYERVERSION_freebsd = "1"

BBLAYERS_LAYERINDEX_NAME_freebsd = "meta-freebsd"

FREEBSD_LAYERDIR = "${LAYERDIR}"
